# Sorts `Cargo.toml` dependencies. All other `.toml` files are formatted with the default config.
#
# https://taplo.tamasfe.dev/configuration/file.html#configuration-file

include = ["Cargo.toml"]
exclude = []

[formatting]
reorder_keys = true
